// react/react-js-tailwind-fontawesome/src/App.jsx
import { faUserSecret } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

function App() {
  return (
    <>
      <h1 className="px-1 py-2 text-3xl font-bold underline">
        Hello world!
        <FontAwesomeIcon icon={faUserSecret} />
      </h1>
    </>
  );
}

export default App;

// angular/angular-tailwind-fontawesome/src/app/app.component.ts
import { Component } from '@angular/core';
import { faCoffee } from '@fortawesome/free-solid-svg-icons';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-tailwind-fontawesome';
  protected readonly faCoffee = faCoffee;
}

<h1 class="p-2 px-1 text-3xl font-bold underline">
  Hello world!<fa-icon [icon]="faCoffee" />
</h1>
